feat: scaffold CountryPeek with routing, Header, and Home shell
PS C:\Users\srini\OneDrive\Documents\countryPeek>  cd country-peek
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> git add

PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> git add .
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.gitignore', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'eslint.config.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package-lock.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/icons.svg', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/App.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'vite.config.js', LF will be replaced by CRLF the next time Git touches it
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek>  git commit -m "feat: scaffold CountryPeek with routing, Header, and Home shell"
[part-1/project-setup d388a22] feat: scaffold CountryPeek with routing, Header, and Home shell
 25 files changed, 2786 insertions(+), 1 deletion(-)
 create mode 100644 .gitignore
 create mode 100644 eslint.config.js
 create mode 100644 index.html
 create mode 100644 package-lock.json
 create mode 100644 package.json
 create mode 100644 public/favicon.svg
 create mode 100644 public/icons.svg
 create mode 100644 src/App.jsx
 create mode 100644 src/components/CountryCard.jsx
 create mode 100644 src/components/FilterBar.jsx
 create mode 100644 src/components/Header.jsx
 create mode 100644 src/components/Loader.jsx
 create mode 100644 src/components/SearchBar.jsx
 create mode 100644 src/context/ThemeContext.jsx
 create mode 100644 src/hooks/useCountries.js
 create mode 100644 src/main.jsx
 create mode 100644 src/pages/CountryPage.jsx
 create mode 100644 src/pages/Favourites.jsx
 create mode 100644 src/pages/Home.jsx
 create mode 100644 src/pages/NotFound.jsx
 create mode 100644 src/store/.gitkeep
 create mode 100644 src/styles/App.css
 create mode 100644 src/styles/index.css
 create mode 100644 vite.config.js
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> git push origin part-1/project-setup
To https://github.com/snivithasri4-ui/country-peek
 ! [rejected]        part-1/project-setup -> part-1/project-setup (non-fast-forward)
error: failed to push some refs to 'https://github.com/snivithasri4-ui/country-peek'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> git pull origin part-1/project-setup --rebase
From https://github.com/snivithasri4-ui/country-peek
 * branch            part-1/project-setup -> FETCH_HEAD
Auto-merging package-lock.json
CONFLICT (add/add): Merge conflict in package-lock.json
Auto-merging package.json
CONFLICT (add/add): Merge conflict in package.json
Auto-merging src/pages/CountryPage.jsx
Auto-merging src/pages/Home.jsx
CONFLICT (add/add): Merge conflict in src/pages/Home.jsx
Auto-merging src/styles/App.css
CONFLICT (add/add): Merge conflict in src/styles/App.css
error: could not apply d388a22... feat: scaffold CountryPeek with routing, Header, and Home shell
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply d388a22... # feat: scaffold CountryPeek with routing, Header, and Home shell
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> git push origin part-1/project-setup
To https://github.com/snivithasri4-ui/country-peek
 ! [rejected]        part-1/project-setup -> part-1/project-setup (non-fast-forward)
error: failed to push some refs to 'https://github.com/snivithasri4-ui/country-peek'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> git push origin part-1/project-setup
To https://github.com/snivithasri4-ui/country-peek
 ! [rejected]        part-1/project-setup -> part-1/project-setup (non-fast-forward)
error: failed to push some refs to 'https://github.com/snivithasri4-ui/country-peek'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\srini\OneDrive\Documents\countryPeek\country-peek> #